### ISSUE TITLE
[BUG]Program can't load mods from savefile or naturally with URL or ID

### ISSUE THREAD

**Issue by WaveNeo98** [g3arshift/Space-Engineers-Mod-Manager#77]
Describe the Bug

After setting up everything, I run the program and try to load the mods from the save file, but it just gets stuck on "Mods Processed" and nothing happens, even if I wait 40 minutes. I've also tried loading them in one by one, but the program can't load them in, even with the URL or ID.To Reproduce

Go to "Add Mods"
Click on "Existing Saves"
Choose the save file
See the error

![Image](https://github.com/user-attachments/assets/e8934a83-c99f-45c3-8713-c0795eb019b6)

Expected Behavior
The mods should load in after some time, and I should be able to manage them.Desktop Environment
OS: Windows 11
Version: 0.7.2 - 0.4.8 - 0.6.2 - 0.7.0

Additional Context
Do you have any idea what could be causing this issue?

**Comment by g3arshift** [comment]
SEMM is still currently in _very_ active development, but I'm surprised that isn't working.

Would you mind sharing the log file it generates, the SEMM_Data.xml file in your storage folder, the sandbox_config.sbc you're modifying, and the URL of the collection it looks like you're trying to add through SEMM?

**Comment by WaveNeo98** [comment]
[datas.zip](https://github.com/user-attachments/files/19592925/datas.zip)

Here is all the requested file.

The mod collection i would like to import to the program from my save file to be able to manage it with a bit more control using the program.

The collection on steam (might need some time because of the automatic check)
https://steamcommunity.com/sharedfiles/filedetails/?id=3457358033&savesuccess=1

**Comment by WaveNeo98** [comment]
Hello, 
Any progress on this matter ?

**Comment by g3arshift** [comment]
Working on try to reproduce this bug, haven't been able to thus far with 0.7.2, but I'm also in the middle of rewriting a significant portion of the application, which may fix this problem in the next version.

**Comment by WaveNeo98** [comment]
Hello, 
Just for an update, I Did checked out the new version 0.8.0 today, the program with the EXE or JAR not even start up, no error or anything tho.

**Comment by g3arshift** [comment]
Figured out what is going on with the no-boot issue. That should be fixed today.

Just so you're aware, SEMM is currently in pre-release development, so there's definitely going to be bugs. We're working hard to polish it for release though, and I really appreciate you taking the time to file bug reports. Just wanted to make sure you were aware of the stage it's currently at.

**Comment by g3arshift** [comment]
Alright, the no boot issue should be fixed.

**Comment by WaveNeo98** [comment]
Hello,
Yes, I understand it's a pre-release program, and honestly, I don't mind bugs, especially if my case can help in any form in the long term. So, don't take any of my message as a rush “do it now or else” sentence. I do have broken English, but I do not mean any harm. :)

Tested out the 8.0.3 version, the program does run without any issue; unfortunately, the issue is still persisting.

![Image](https://github.com/user-attachments/assets/e51d223f-6174-4eb2-9db5-26c91b300a7b)

**Comment by g3arshift** [comment]
Glad to have you here, and bug reports definitely help.

I've been having some trouble actually replicating your issue though. I've gotten the collection you're trying to add to function [(this one)](https://steamcommunity.com/sharedfiles/filedetails/?id=3457358033&savesuccess=1), and adding from my own existing saves works as well.

Could you send me the following:
1. The Sandbox_config.sbc you're trying to add mods from. This is in the folder your SE save is in.
2. The Sandbox.sbc you're trying to add mods from. This is in the folder your SE save is in.
3. The SEMM.log file located in the logs folder wherever you've put the application.
That behavior where you're seeing it load forever is a bug I've been trying to chase down, and it indicates that there's been some error with the web scraping part of the application. On that topic, what are your internet speeds?

**Comment by g3arshift** [comment]
I've just pushed out an update that should prevent your UI from locking up like it has been. This should also give an error in your log that will help me diagnose this problem, so make sure to download 0.8.0.4.

**Comment by WaveNeo98** [comment]
Hello,
Soo i tried it with the new version, from save and from the modlist it is stuck again on processing, tried to reduce the modpack (70-80) but still the same issue. 
I had an idea to try it out on my work laptop without the game, sadly same process error again, can't even complete the tutorial option because of this.
Regarding the internet, for both device 950/400mbps with 2-3 ms ping, also tried with different network (mobile network with lover speed) but nothing.

Inside of the ZIP there is the full save file and the SEMM after using it (both from the main pc)

https://drive.google.com/file/d/10yX5w60qbk99XgOiHRxFIj9fTaCkjbit/view?usp=sharing

**Comment by g3arshift** [comment]
I couldn't replicate it even with your files, but it did give me an idea.

What is your system/browser language set to?

**Comment by g3arshift** [comment]
I'm now able to replicate this. Non-english systems currently break SEMM as of 0.8.0.4, but it should be fixed in 0.8.0.5.

**Comment by WaveNeo98** [comment]
Hello,
For my systems the language is Hungarian.

**Comment by g3arshift** [comment]
0.8.0.5 will be out within a few minutes and should fix this issue, please let me know if it does!

**Comment by g3arshift** [comment]
0.8.0.5 had some unrelated issues that would prevent you from using steam mods, make sure you're using at least 0.8.0.6.

**Comment by WaveNeo98** [comment]
Hello, Sorry for the late answer, week got complicated at work.
Sooo i tested the new version 0.8.0.7 and here is the log for the errors, but progress cause the program now didn't stuck.
Tried using my save file to import mods and also tried the manual one by one with the "add mods from" button

https://drive.google.com/file/d/1tJYOJXKIWG7KDhze3ToZchXwL4k83N10/view?usp=sharing

**Comment by g3arshift** [comment]
Looks like the date is failing to process again for whatever reason. I'll get a fix out for 0.8.0.9.

**Comment by g3arshift** [comment]
Just pushed another fix for this that should, hopefully, properly fix it this time. I'd gotten most of the way previously, but it seems that it was still using international datetime formatting, which I hadn't expected. Try 0.8.0.9.

**Comment by WaveNeo98** [comment]
Hello,

I hope you have some great time regarding the long weekend break.
I think now there is a light in the end of the cave, Mod's has been processed, not all of them but 80% is downloaded, others giving some kind of error for further investigation. 

https://drive.google.com/file/d/1WnHp3-1oeV8E4mZAUdoLsCt5RATjOZMz/view?usp=sharing

**Comment by g3arshift** [comment]
It was more date parsing errors due to it expecting system language (Hungarian) date formats which are I think, using September as an example, are in the format like "Szept". That should be fixed, though it's going to use English representation of dates, at least for now.

That should be fixed in 0.8.0.10, along with a slew of other problems. There were a few timeouts occurring in the logs, but I'm not sure if that's an issue with the program or something else. Either way, give 0.8.0.10 a try.

**Comment by WaveNeo98** [comment]
Hello,
Now I'm happy too say that there is no more issue so far , all the mod's are downloaded without a problem.

**Comment by g3arshift** [comment]
Awesome! I'm going to close this issue then. Let me know if you have any more issues with this bug or anything else!
